/**
 * Tool: draftAnnouncement
 * Generate a professional team announcement draft.
 * Does NOT send it — returns the draft text for the user to review and post themselves.
 */

export const definition = {
  type: 'function',
  function: {
    name: 'draftAnnouncement',
    description:
      'Draft a professional team announcement message. ' +
      'Returns the text so the user can review and post it to the project chat. ' +
      'Use this when asked to write a message, reminder, or announcement for the team.',
    parameters: {
      type: 'object',
      properties: {
        topic: {
          type: 'string',
          description: 'The subject or purpose of the announcement (e.g. "timesheet reminder", "deadline warning").',
        },
        tone: {
          type: 'string',
          enum: ['professional', 'friendly', 'urgent'],
          description: 'The tone of the message. Defaults to "professional".',
        },
        extra_details: {
          type: 'string',
          description: 'Any additional details to include in the announcement.',
        },
        deadline: {
          type: 'string',
          description: 'A specific deadline or date to reference in the announcement.',
        },
      },
      required: ['topic'],
    },
  },
};

/**
 * This tool generates the draft inline — no DB call needed.
 * The AI model itself composes the text based on the parameters.
 */
export async function execute(args) {
  const { topic, tone = 'professional', extra_details, deadline } = args;

  // This tool returns instructions to the AI to compose the draft itself.
  // The actual announcement text is generated by the model in its final response.
  return {
    instruction: 'compose_announcement',
    topic,
    tone,
    deadline:      deadline      || null,
    extra_details: extra_details || null,
    note: 'Generate the announcement text in your response. Format it clearly with a subject line and body. Remind the user to copy and paste it into the project chat.',
  };
}
